/**
 * Where a question is asked, and where the answer has to justify itself.
 *
 * The panel is built around one rule the backend enforces: an answer is only shown when the
 * platform found evidence, and it is always shown with the passages it came from and the
 * trace of how it was produced. `insufficient_evidence` is therefore rendered as a result —
 * with the counts that explain it — not as an error, because it is the platform working.
 *
 * `top_k` and `min_score` are exposed because they are the two knobs that change what
 * retrieval does, and seeing the trace change with them is the point of this screen. The
 * ranges are checked here for immediate feedback; the backend validates them again.
 */

import { useState } from 'react'
import type { FormEvent, ReactNode } from 'react'

import { ApiError, asApiError } from '../../api/client'
import { api } from '../../api/endpoints'
import type { Citation, QueryResponse } from '../../api/types'
import { ErrorState, Loading } from '../../components/states'
import { formatCount, formatScore, formatTokens } from '../../lib/format'
import { TraceDetails } from './TraceDetails'

interface Exchange {
  id: number
  question: string
  topK: number | undefined
  minScore: number | undefined
  pending: boolean
  result: QueryResponse | null
  error: ApiError | null
}

/** `undefined` means "not given", and the string `'invalid'` means the field cannot be used. */
function parseOptional(raw: string): number | undefined | 'invalid' {
  const trimmed = raw.trim()
  if (trimmed === '') {
    return undefined
  }
  const value = Number(trimmed)
  return Number.isFinite(value) ? value : 'invalid'
}

function CitationList({ citations }: { citations: Citation[] }): ReactNode {
  if (citations.length === 0) {
    return null
  }
  return (
    <ol className="citations">
      {citations.map((citation) => (
        <li className="citation" key={citation.chunk_id}>
          <div className="citation__head">
            <span>
              <span className="citation__marker">[{citation.marker}]</span> {citation.document_name}
              {citation.heading_path.length > 0 ? ` › ${citation.heading_path.join(' › ')}` : ''}
            </span>
            <span className="mono">
              chunk #{citation.chunk_index} · score {formatScore(citation.score)}
              {citation.rerank_score !== null
                ? ` · rerank ${formatScore(citation.rerank_score)}`
                : ''}
              {citation.page_number !== null ? ` · page ${citation.page_number}` : ''}
            </span>
          </div>
          <p className="citation__snippet">{citation.snippet}</p>
        </li>
      ))}
    </ol>
  )
}

function Answer({ result }: { result: QueryResponse }): ReactNode {
  if (result.outcome === 'insufficient_evidence') {
    return (
      <div className="state state--empty">
        <p className="state__title">Not enough evidence in this knowledge base</p>
        <p className="state__body">
          Retrieval returned {formatCount(result.trace.retrieval.candidates)} candidate
          {result.trace.retrieval.candidates === 1 ? '' : 's'} and{' '}
          {formatCount(result.trace.retrieval.above_threshold)} cleared the similarity
          threshold of {result.trace.retrieval.min_score}. Nothing was sent to the generator, so
          nothing was invented: no <code>generation</code> stage ran for this question.
        </p>
      </div>
    )
  }

  return (
    <>
      <div className="answer">{result.answer}</div>
      <p className="card__hint">
        {result.answer_kind === 'extractive'
          ? 'Extractive answer: the passages below are returned verbatim, no model wrote this text.'
          : `Generated by ${result.trace.generation?.model ?? 'a model'} from the passages below.`}{' '}
        Tokens: {formatTokens(result.usage.input_tokens, result.usage.output_tokens)}.
      </p>
      <CitationList citations={result.citations} />
    </>
  )
}

export function QueryPanel({ knowledgeBaseId }: { knowledgeBaseId: string }): ReactNode {
  const [question, setQuestion] = useState('')
  const [topK, setTopK] = useState('')
  const [minScore, setMinScore] = useState('')
  const [exchanges, setExchanges] = useState<Exchange[]>([])
  const [asking, setAsking] = useState(false)
  const [formError, setFormError] = useState<string | null>(null)
  const [nextId, setNextId] = useState(1)

  const questionPlaceholder = 'How often do database credentials rotate?'

  async function ask(event: FormEvent): Promise<void> {
    event.preventDefault()
    const trimmed = question.trim()
    if (trimmed === '') {
      setFormError('Enter a question.')
      return
    }

    const parsedTopK = parseOptional(topK)
    const parsedMinScore = parseOptional(minScore)
    if (parsedTopK === 'invalid' || parsedMinScore === 'invalid') {
      setFormError('Top-k and minimum score must be numbers.')
      return
    }
    if (parsedTopK !== undefined && (!Number.isInteger(parsedTopK) || parsedTopK < 1 || parsedTopK > 50)) {
      setFormError('Top-k must be a whole number between 1 and 50.')
      return
    }
    if (parsedMinScore !== undefined && (parsedMinScore < -1 || parsedMinScore > 1)) {
      setFormError('Minimum score must be between -1 and 1.')
      return
    }

    setFormError(null)
    const id = nextId
    setNextId(id + 1)
    setAsking(true)
    setExchanges((current) => [
      {
        id,
        question: trimmed,
        topK: parsedTopK,
        minScore: parsedMinScore,
        pending: true,
        result: null,
        error: null,
      },
      ...current,
    ])
    setQuestion('')

    try {
      const result = await api.query(knowledgeBaseId, {
        question: trimmed,
        ...(parsedTopK !== undefined ? { top_k: parsedTopK } : {}),
        ...(parsedMinScore !== undefined ? { min_score: parsedMinScore } : {}),
      })
      setExchanges((current) =>
        current.map((exchange) =>
          exchange.id === id ? { ...exchange, pending: false, result } : exchange,
        ),
      )
    } catch (thrown) {
      const error = asApiError(thrown)
      setExchanges((current) =>
        current.map((exchange) =>
          exchange.id === id ? { ...exchange, pending: false, error } : exchange,
        ),
      )
    } finally {
      setAsking(false)
    }
  }

  return (
    <section>
      <div className="card">
        <div className="card__header">
          <h2>Ask a question</h2>
        </div>
        <form onSubmit={(event) => void ask(event)}>
          <div className="field">
            <label htmlFor="question">Question</label>
            <textarea
              id="question"
              rows={2}
              maxLength={2000}
              value={question}
              placeholder={questionPlaceholder}
              onChange={(event) => {
                setQuestion(event.target.value)
              }}
            />
          </div>
          <div className="row" style={{ marginTop: '0.6rem' }}>
            <div className="field">
              <label htmlFor="top-k">Passages (top-k)</label>
              <input
                id="top-k"
                inputMode="numeric"
                value={topK}
                placeholder="server default"
                onChange={(event) => {
                  setTopK(event.target.value)
                }}
              />
            </div>
            <div className="field">
              <label htmlFor="min-score">Minimum score</label>
              <input
                id="min-score"
                inputMode="decimal"
                value={minScore}
                placeholder="server default"
                onChange={(event) => {
                  setMinScore(event.target.value)
                }}
              />
            </div>
            <button type="submit" className="button button--primary" disabled={asking}>
              {asking ? 'Asking…' : 'Ask'}
            </button>
          </div>
        </form>
        {formError ? <p style={{ color: 'var(--error)' }}>{formError}</p> : null}
        <p className="card__hint" style={{ marginBottom: 0 }}>
          Raising the minimum score makes the platform report missing evidence sooner and keeps
          weaker passages out of the answer. The trace shows what each value did.
        </p>
      </div>

      {exchanges.length === 0 ? (
        <p className="card__hint">
          Answers appear here with their citations and the stage-by-stage trace.
        </p>
      ) : null}

      {exchanges.map((exchange) => (
        <div className="card" key={exchange.id}>
          <div className="card__header">
            <h2>{exchange.question}</h2>
            <span className="mono" style={{ color: 'var(--text-muted)' }}>
              {exchange.topK !== undefined ? `top_k ${exchange.topK}` : 'top_k default'}
              {exchange.minScore !== undefined ? ` · min_score ${exchange.minScore}` : ''}
            </span>
          </div>

          {exchange.pending ? <Loading label="Retrieving evidence…" /> : null}
          {exchange.error ? <ErrorState error={exchange.error} /> : null}
          {exchange.result ? (
            <>
              <Answer result={exchange.result} />
              <TraceDetails
                trace={exchange.result.trace}
                citations={exchange.result.citations.length}
                outcome={exchange.result.outcome}
              />
            </>
          ) : null}
        </div>
      ))}
    </section>
  )
}
